# Generated by Django 4.2.20 on 2025-04-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='serial',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/serials/breakingBad.webp.webp'),
        ),
    ]
