# Generated by Django 4.2.20 on 2025-04-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/movies/'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/serials/'),
        ),
    ]
