# Generated by Django 4.2.20 on 2025-04-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_add_subscription_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'verbose_name': 'Сериал', 'verbose_name_plural': 'Сериалы'},
        ),
    ]
