# Generated by Django 4.2.20 on 2025-04-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_create_moderator_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=20),
        ),
    ]
