# Generated by Django 4.2.20 on 2025-04-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(db_index=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='release_year',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'release_year'], name='Main_movie_title_0c58ae_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_year'], name='Main_movie_release_b57eac_idx'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=models.Index(fields=['title', 'release_year'], name='Main_serial_title_715ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=models.Index(fields=['release_year'], name='Main_serial_release_191713_idx'),
        ),
    ]
