# Generated by Django 4.2.20 on 2025-05-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_country_name_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movie_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Изображение фильма',
                'verbose_name_plural': 'Изображения фильмов',
            },
        ),
        migrations.CreateModel(
            name='SerialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='serial_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Изображение сериала',
                'verbose_name_plural': 'Изображения сериалов',
            },
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='Main_movie_title_0c58ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='Main_movie_release_b57eac_idx',
        ),
        migrations.RemoveIndex(
            model_name='serial',
            name='Main_serial_title_715ff3_idx',
        ),
        migrations.RemoveIndex(
            model_name='serial',
            name='Main_serial_release_191713_idx',
        ),
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг Кинопоиска'),
        ),
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL на Кинопоиске'),
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL для просмотра'),
        ),
        migrations.AddField(
            model_name='serial',
            name='kinopoisk_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг Кинопоиска'),
        ),
        migrations.AddField(
            model_name='serial',
            name='kinopoisk_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL на Кинопоиске'),
        ),
        migrations.AddField(
            model_name='serial',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL трейлера'),
        ),
        migrations.AddField(
            model_name='serial',
            name='watch_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL для просмотра'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='release_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='serialimage',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Main.serial'),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Main.movie'),
        ),
    ]
