# Generated by Django 4.2.20 on 2025-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_movieimage_serialimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сериал', 'verbose_name_plural': 'Сериалы'},
        ),
        migrations.AlterField(
            model_name='serial',
            name='country',
            field=models.ManyToManyField(to='Main.country', verbose_name='Страны'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='episodes',
            field=models.PositiveIntegerField(verbose_name='Количество эпизодов'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='genres',
            field=models.ManyToManyField(to='Main.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/serials/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
