# Generated by Django 4.2.20 on 2025-05-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_alter_movie_options_alter_serial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='kinopoisk_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID на Кинопоиске'),
        ),
    ]
